[package]
name = "cargo-vet"
version = "0.1.0"
edition = "2021"
authors = ["Bobby Holley <bobbyholley@gmail.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/bholley/cargo-vet"
homepage = "https://bholley.net/cargo-vet"
description = "Supply-chain security for Rust"
exclude = [
  "book/*",
  "src/snapshots/*",
  "src/tests.rs",
  "tests/",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_metadata = "0.14.2"
clap = "3.1.10"
clap-cargo = "0.8.0"
console = "0.15.0"
eyre = "0.6.8"
flate2 = { version = "1.0.24", default-features = false, features = ["zlib"] }
home = "0.5.3"
nom = "7.1.1"
reqwest = { version = "0.11.10", features = ["blocking"] }
serde = "1.0.136"
serde_json = "1.0.79"
tar = { version = "0.4.26", default-features = false }
tempfile = "3.3.0"
textwrap = { version = "0.15", default-features = false }
toml = "0.5.8"
tracing = { version = "0.1.34", features = ["log"] }
tracing-subscriber = "0.3.11"

[dev-dependencies]
insta = "1.13.0" 
